c_compiler:
  - gcc
c_compiler_version:
  - 7
cxx_compiler:
  - gxx
cxx_compiler_version:
  - 7
channel_sources:
  - local,conda-forge,anaconda
fortran_compiler:
  - gfortran
fortran_compiler_version:
  - 7
fftw:
  - 3
hdf4:
  - 4.2
hdf5:
  - 1.10.5
jasper:
  - 1.900.1
jpeg:
  - 9
libnetcdf:
  - 4.7.4
mpi:
  - nompi
  - openmpi
netcdf_fortran:
  - 4.5
numpy:
  - 1.16
  - 1.19
openmpi:
  - 4.0
perl:
  - 5.26.2
python:
  - 3.6.* *_cpython    # [not (osx and arm64)]
  - 3.8.* *_cpython
rttov:
  - 13.0
zlib:
  - 1.2
